CREATE TABLE IF NOT EXISTS
BILLIONAIRE (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    RANK VARCHAR(255),
    NETWORTH VARCHAR(255),
    COMPANIESOWNED VARCHAR(255)
);

CREATE SEQUENCE IF NOT EXISTS HIBERNATE_SEQUENCE;